/**
 * @addtogroup examplesdcpsTrackisocpp
 */
/** @{*/
/** @file */

module TrackData
{
   struct Track
   {
      /** Track ID */
      long tId;
      /**  xPos */
      long xPos;
      /**  yPos */
      long yPos;
   };
   #pragma keylist Track tId
};

/** @}*/
